package online.lcelectronics.api.enums;

public enum Component {

    ACCESSORIES, // TV, STEREO AND MICROWAVES
    MAIN_BOARD, // TV
    POWER_BOARD,// TV AND STEREO
    BOARD_WIFI, // TV
    T_COM_BOARD, // TV
    DISPLAY_PANEL, // TV
    LED_BAR, // TV
    DIFFUSER_SHEET, // TV
    TUNER, // TV
    SPEAKERS, // TV AND STEREO
    AMPLIFIER_CARD, //STEREO
    USB_BLUETOOTH_CARD, // STEREO
    WOOFER_SPEAKER, //STEREO
    TWEETER_SPEAKER, // STEREO
    BAFFLE, // STEREO
    DISPLAY_CARD,    // STEREO AND MICROWAVES
    MAGNETRON, //MICROWAVES
    HIGH_VOLTAGE_TRANSFORMER, //MICROWAVES
    KEYBOARD, //MICROWAVES AND TV
    FLAT_MOTOR, //MICROWAVES
    FAN_MOTOR, //MICROWAVES
    DOOR_BUTTON, //MICROWAVES
    GATE_SWITCH, //MICROWAVES
    REFRACTORY_PLATE, //MICROWAVES
    OTHERS //TV, STEREO AND MICROWAVES

}
