package online.lcelectronics.api.enums;

public enum Component {

    ACCESSORIES, // TV, STEREO AND MICROWAVES
    AMPLIFIER_CARD, //STEREO
    BAFFLE, // STEREO
    BOARD_WIFI, // TV
    DIFFUSER_SHEET, // TV
    DISPLAY_CARD,    // STEREO AND MICROWAVES
    DISPLAY_PANEL, // TV
    DOOR_BUTTON, //MICROWAVES
    FAN_MOTOR, //MICROWAVES
    FLAT_MOTOR, //MICROWAVES
    GATE_SWITCH, //MICROWAVES
    HIGH_VOLTAGE_TRANSFORMER, //MICROWAVES
    KEYBOARD, //MICROWAVES AND TV
    LED_BAR, // TV
    MAGNETRON, //MICROWAVES
    MAIN_BOARD, // TV
    OTHERS, //TV, STEREO AND MICROWAVES
    POWER_BOARD,// TV AND STEREO
    REFRACTORY_PLATE, //MICROWAVES
    SPEAKERS, // TV AND STEREO
    T_COM_BOARD, // TV
    TUNER, // TV
    TWEETER_SPEAKER, // STEREO
    USB_BLUETOOTH_CARD, // STEREO
    WOOFER_SPEAKER //STEREO

}
