name: Java CI with Maven

on:
  push:
    branches:
      - 'api-*'
  pull_request:
    branches:
      - 'dev-*'
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Find modified files
        id: diff
        run: |
          echo "::set-output name=modified::$(git diff --name-only HEAD^ | grep src/main/java | sed 's/src\/main\/java\///' | sed 's/.java//' | tr '/' '.' | tr '\n' ',')"
      - name: Run tests
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            mvn -Dtest=${{ steps.diff.outputs.modified }} test
          else
            mvn test
          fi
